<?php

namespace Database\Seeders;

use App\Models\Trip;
use Illuminate\Database\Seeder;

class TripSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Trip::query()->delete();

        $trips = [
            // Signature Journeys (featured on the homepage)
            [
                'title' => 'The Cairo Experience',
                'slug' => 'the-cairo-experience',
                'image' => 'images/home/trip-cairo.png',
                'price' => 1299,
                'original_price' => 1599,
                'duration' => '4 Days',
                'location' => 'Cairo',
                'rating' => 4.8,
                'reviews_count' => 312,
                'destination_category' => 'Cairo & Giza',
                'trip_type' => 'Historical Discovery',
                'group_size' => '2 - 14 Travelers',
                'is_featured' => true,
                'description' => "Step into the cradle of civilization with an immersive journey through Cairo and Giza. From the timeless silhouette of the Great Pyramids to the labyrinthine alleys of Khan el-Khalili, this curated escape pairs ancient wonder with five-star comfort, guided every step of the way by a licensed Egyptologist.",
                'highlights' => [
                    'Private guided tour of the Great Pyramids & Sphinx of Giza',
                    'Skip-the-line access to the Egyptian Museum\'s royal mummy hall',
                    'Sunset felucca ride on the Nile',
                    'Exploration of Islamic Cairo & the Khan el-Khalili bazaar',
                    'Stay in a 4-star Nile-view hotel with daily breakfast',
                ],
                'itinerary' => [
                    ['day' => 1, 'title' => 'Arrival & Giza Plateau', 'description' => 'Land in Cairo and transfer to your hotel. In the afternoon, visit the Great Pyramids of Khufu, Khafre, and Menkaure, followed by the Great Sphinx.'],
                    ['day' => 2, 'title' => 'Egyptian Museum & Islamic Cairo', 'description' => 'Discover the treasures of Tutankhamun at the Egyptian Museum, then wander the historic streets of Islamic Cairo and the Khan el-Khalili bazaar.'],
                    ['day' => 3, 'title' => 'Saqqara & Memphis', 'description' => 'Venture to Saqqara to see the Step Pyramid of Djoser, then continue to Memphis, the ancient capital, before an evening Nile felucca ride.'],
                    ['day' => 4, 'title' => 'Leisure & Departure', 'description' => 'Enjoy a relaxed morning at leisure or optional shopping before your transfer to the airport.'],
                ],
                'includes' => [
                    ['title' => 'Airport pick-up and drop-off in a private air-conditioned vehicle', 'description' => 'A professional driver meets you at arrivals with a name board and returns you to the airport on departure day in a comfortable, climate-controlled private vehicle.'],
                    ['title' => '3 nights in a 4-star hotel with daily breakfast', 'description' => 'Centrally located hotel with Nile or Pyramid views, offering a full daily breakfast each morning to start every day of sightseeing in the right spirit.'],
                    ['title' => 'Licensed Egyptologist guide throughout', 'description' => 'Your personal guide holds a university degree in Egyptology and brings every monument to life with expert storytelling, historical context, and insider knowledge.'],
                    ['title' => 'All entrance fees listed in the itinerary', 'description' => 'Pre-paid access to the Giza Plateau, Egyptian Museum, Saqqara, and all sites on the day-by-day itinerary — no queuing at ticket booths.'],
                    ['title' => 'Bottled water during tours', 'description' => 'Chilled bottled water is provided throughout each touring day to keep you hydrated under the Egyptian sun.'],
                ],
                'excludes' => [
                    ['title' => 'International flights', 'description' => 'Flights to and from Cairo are not included. Our concierge team can assist with flight search and booking recommendations if needed.'],
                    ['title' => 'Egypt entry visa', 'description' => 'Most nationalities obtain an e-Visa online before travel or on arrival at Cairo Airport. We will confirm the exact requirement for your passport nationality before departure.'],
                    ['title' => 'Lunches and dinners', 'description' => 'Dining out is at your own expense, giving you the freedom to explore Cairo\'s vibrant food scene. Your guide is happy to suggest the best local restaurants.'],
                    ['title' => 'Gratuities for guides and drivers', 'description' => 'Tips are not included and entirely discretionary. A tipping guideline for Egypt will be provided in your pre-departure information pack.'],
                    ['title' => 'Personal expenses and souvenirs', 'description' => 'Shopping, personal purchases, and any items beyond those listed in the itinerary are at your own cost.'],
                ],
                'gallery' => [
                    'images/home/hero-pyramids.png',
                    'images/destinations/dest-cairo.png',
                    'images/home/gallery-islamic-cairo.png',
                    'images/home/gallery-bazaar.png',
                ],
                'accommodations' => [
                    [
                        'name' => 'Cairo Pyramids View Hotel',
                        'location' => 'Giza',
                        'nights' => 2,
                        'rating' => 5,
                        'image' => 'images/contact/office-cairo-pyramids-view.png',
                        'description' => 'A 5-star hotel with private balconies overlooking the Great Pyramids, just minutes from the Giza Plateau.',
                    ],
                    [
                        'name' => 'Nile Corniche Boutique Hotel',
                        'location' => 'Cairo',
                        'nights' => 1,
                        'rating' => 4,
                        'image' => 'images/about/mission-nile-balcony-twilight.png',
                        'description' => 'An elegant riverside boutique stay with rooftop dining and panoramic views of the Nile.',
                    ],
                ],
                'rating_breakdown' => [
                    'itinerary' => 4.9,
                    'transportation' => 4.7,
                    'value' => 4.8,
                    'accommodation' => 4.8,
                    'tour_guide' => 4.9,
                ],
                'reviews' => [
                    [
                        'name' => 'Sarah Mitchell',
                        'country' => 'United Kingdom',
                        'date' => 'May 2026',
                        'rating' => 5,
                        'text' => "Our guide brought the pyramids to life with stories you'd never find in a guidebook, and waking up to a pyramid view from the Giza hotel was unreal.",
                        'photos' => [
                            'images/home/hero-pyramids.png',
                            'images/destinations/dest-cairo.png',
                        ],
                    ],
                    [
                        'name' => 'Marco Rossi',
                        'country' => 'Italy',
                        'date' => 'March 2026',
                        'rating' => 5,
                        'text' => 'Khan el-Khalili at sunset was magical and skipping the museum queues saved us hours. Highly recommend this exact itinerary.',
                    ],
                    [
                        'name' => 'Emma Müller',
                        'country' => 'Germany',
                        'date' => 'January 2026',
                        'rating' => 4,
                        'text' => "Wonderful pacing for a short trip - Saqqara was a real highlight we wouldn't have found alone. Just wished for one more day in Cairo.",
                    ],
                ],
                'faqs' => [
                    [
                        'question' => "Is 4 days enough time to see Cairo's major sites?",
                        'answer' => "Yes - this itinerary is designed to cover the Giza Plateau, Egyptian Museum, Saqqara, and Islamic Cairo efficiently with a private guide, so you won't waste time in queues or traffic.",
                    ],
                    [
                        'question' => 'Can I combine this trip with a Nile cruise to Luxor?',
                        'answer' => "Absolutely. Many travelers extend with our Kingdom of Luxor itinerary - just let your concierge know when booking and we'll arrange a seamless connection.",
                    ],
                ],
            ],
            [
                'title' => 'Kingdom of Luxor',
                'slug' => 'kingdom-of-luxor',
                'image' => 'images/home/trip-luxor.png',
                'price' => 1850,
                'original_price' => null,
                'duration' => '5 Days',
                'location' => 'Luxor',
                'rating' => 4.9,
                'reviews_count' => 198,
                'destination_category' => 'Upper Egypt (Luxor/Aswan)',
                'trip_type' => 'Historical Discovery',
                'group_size' => '2 - 12 Travelers',
                'is_featured' => true,
                'description' => "Cross to the East and West Banks of ancient Thebes, where pharaohs built their temples and carved their tombs deep into the Theban hills. This journey blends grand monuments with a sunrise hot air balloon ride over the Valley of the Kings for an unforgettable perspective on Egypt's golden age.",
                'highlights' => [
                    'Sunrise hot air balloon ride over the Valley of the Kings',
                    'Guided tour of the Valley of the Kings royal tombs',
                    'Karnak Temple complex and Luxor Temple at night',
                    'Hatshepsut\'s Mortuary Temple at Deir el-Bahari',
                    'Colossi of Memnon photo stop',
                ],
                'itinerary' => [
                    ['day' => 1, 'title' => 'Arrival in Luxor', 'description' => 'Arrive and settle into your Nile-view hotel. Evening visit to the illuminated Luxor Temple.'],
                    ['day' => 2, 'title' => 'Hot Air Balloon & Valley of the Kings', 'description' => 'Rise before dawn for a balloon ride over the West Bank, then explore the Valley of the Kings and Hatshepsut\'s Temple.'],
                    ['day' => 3, 'title' => 'Karnak & Colossi of Memnon', 'description' => 'Spend the morning at the vast Karnak Temple complex, followed by a stop at the Colossi of Memnon.'],
                    ['day' => 4, 'title' => 'Free Day on the Nile', 'description' => 'A leisurely day with an optional felucca sail along the Nile or relaxation at your hotel.'],
                    ['day' => 5, 'title' => 'Departure', 'description' => 'Final morning at leisure before transfer to Luxor International Airport.'],
                ],
                'includes' => [
                    ['title' => '4 nights in a luxury Nile-view hotel with daily breakfast', 'description' => 'Handpicked 5-star properties overlooking the Nile with all-day concierge service and a full breakfast each morning to fuel your temple explorations across Luxor\'s East and West Banks.'],
                    ['title' => 'Sunrise hot air balloon ride', 'description' => 'A licensed dawn flight with a safety-certified operator above the Valley of the Kings and the Theban Hills — one of Egypt\'s most unforgettable experiences, operated weather permitting with full safety briefing.'],
                    ['title' => 'Licensed Egyptologist guide', 'description' => 'Your dedicated guide holds a degree in Egyptology and provides expert interpretation of hieroglyphs, pharaonic history, and temple symbolism at every site visited.'],
                    ['title' => 'All entrance fees listed in the itinerary', 'description' => 'Temple tickets, tomb entry permits, and access to all monuments on the day-by-day itinerary are pre-paid — you never queue at a ticket booth.'],
                    ['title' => 'Private air-conditioned transport', 'description' => 'Comfortable private vehicles throughout — airport pick-up on arrival, all transfers between the East and West Banks, and drop-off at the airport on departure day.'],
                ],
                'excludes' => [
                    ['title' => 'Flights to and from Luxor', 'description' => 'International and domestic flights are not included. Our concierge can assist with flight recommendations and booking if needed before your trip.'],
                    ['title' => 'Egypt entry visa', 'description' => 'Most nationalities can obtain an e-Visa online before travel or on arrival at major airports. Our team will advise on the exact requirement for your passport.'],
                    ['title' => 'Lunches and dinners', 'description' => 'Meals beyond the included daily breakfast are at your own expense, giving you the flexibility to discover Luxor\'s excellent restaurant scene. Your guide can recommend local favorites.'],
                    ['title' => 'Gratuities', 'description' => 'Tips for guides, drivers, and hotel staff are not included and are entirely at your discretion. A tipping guideline will be provided in your pre-departure documents.'],
                    ['title' => 'Optional felucca sail', 'description' => 'A relaxed sunset felucca ride along the Nile can be arranged as a paid add-on to your free day — ask your concierge at the time of booking.'],
                ],
                'gallery' => [
                    'images/destinations/dest-luxor.png',
                    'images/about/hero-luxor-temple-sunset.png',
                    'images/about/legacy-dahabiya-nile-dawn.png',
                    'images/about/mission-nile-balcony-twilight.png',
                ],
                'accommodations' => [
                    [
                        'name' => 'Luxor Nile Sunset Resort',
                        'location' => 'Luxor East Bank',
                        'nights' => 3,
                        'rating' => 5,
                        'image' => 'images/contact/office-luxor-nile-sunset.png',
                        'description' => 'A riverside 5-star resort with an infinity pool overlooking the West Bank temples.',
                    ],
                    [
                        'name' => 'Winter Palace Heritage Hotel',
                        'location' => 'Luxor',
                        'nights' => 1,
                        'rating' => 5,
                        'image' => 'images/about/hero-luxor-temple-sunset.png',
                        'description' => 'A grand colonial-era hotel steps from Luxor Temple, steeped in old-world elegance.',
                    ],
                ],
                'rating_breakdown' => [
                    'itinerary' => 5.0,
                    'transportation' => 4.8,
                    'value' => 4.7,
                    'accommodation' => 4.9,
                    'tour_guide' => 5.0,
                ],
                'reviews' => [
                    [
                        'name' => 'James Anderson',
                        'country' => 'United States',
                        'date' => 'April 2026',
                        'rating' => 5,
                        'text' => "The sunrise balloon ride over the Valley of the Kings is something I'll never forget, and the Winter Palace made us feel like royalty.",
                        'photos' => [
                            'images/destinations/dest-luxor.png',
                            'images/about/hero-luxor-temple-sunset.png',
                        ],
                    ],
                    [
                        'name' => 'Sophie Dubois',
                        'country' => 'France',
                        'date' => 'February 2026',
                        'rating' => 5,
                        'text' => "Karnak Temple lit up at night was breathtaking, and our guide's depth of knowledge on the hieroglyphs added so much.",
                    ],
                    [
                        'name' => 'Liam O\'Connor',
                        'country' => 'Ireland',
                        'date' => 'December 2025',
                        'rating' => 4,
                        'text' => 'Excellent itinerary and lovely hotels. The free day let us relax by the Nile after a few busy days of sightseeing.',
                    ],
                ],
                'faqs' => [
                    [
                        'question' => 'Is the hot air balloon ride safe and suitable for everyone?',
                        'answer' => 'Yes - our balloon excursions use licensed operators with strong safety records. It is suitable for most travelers, though we recommend mentioning any mobility concerns when booking.',
                    ],
                    [
                        'question' => 'What should I wear when visiting the temples?',
                        'answer' => 'Light, breathable clothing that covers shoulders and knees is recommended, along with comfortable walking shoes, a hat, and sunscreen - temple floors can be uneven and the sun is strong.',
                    ],
                ],
            ],
            [
                'title' => 'Red Sea Serenity',
                'slug' => 'red-sea-serenity',
                'image' => 'images/home/trip-redsea.png',
                'price' => 1420,
                'original_price' => 1750,
                'duration' => '6 Days',
                'location' => 'Hurghada',
                'rating' => 4.8,
                'reviews_count' => 145,
                'destination_category' => 'Red Sea Riviera',
                'trip_type' => 'Wellness & Retreat',
                'group_size' => '2 - 20 Travelers',
                'is_featured' => true,
                'description' => "Trade temples for turquoise water on this all-inclusive escape to the Red Sea Riviera. Unwind on private beaches, glide over vibrant coral reefs, and let our spa therapists melt away every trace of travel fatigue at a beachfront resort designed for pure relaxation.",
                'highlights' => [
                    'All-inclusive stay at a private beachfront resort',
                    'Guided snorkeling excursion over coral reefs',
                    'Sunset yacht cruise along the coast',
                    'Two-session spa & wellness package',
                    'Optional desert safari add-on',
                ],
                'itinerary' => [
                    ['day' => 1, 'title' => 'Arrival & Resort Check-in', 'description' => 'Arrive in Hurghada and settle into your beachfront resort. Evening at leisure.'],
                    ['day' => 2, 'title' => 'Coral Reef Snorkeling', 'description' => 'Board a boat to nearby reefs for a guided snorkeling adventure among colorful marine life.'],
                    ['day' => 3, 'title' => 'Spa & Wellness Day', 'description' => 'A full day dedicated to relaxation with a spa treatment session and resort amenities.'],
                    ['day' => 4, 'title' => 'Sunset Yacht Cruise', 'description' => 'Sail along the coastline as the sun sets, with refreshments served on board.'],
                    ['day' => 5, 'title' => 'Leisure / Optional Desert Safari', 'description' => 'Free day to relax, or join an optional 4x4 desert safari with Bedouin dinner.'],
                    ['day' => 6, 'title' => 'Departure', 'description' => 'Check out and transfer to Hurghada International Airport.'],
                ],
                'includes' => [
                    ['title' => '5 nights at a beachfront resort, breakfast & dinner daily', 'description' => 'An all-inclusive stay at a private beachfront property with a full breakfast and dinner each day, plus unlimited use of pools, private beach, and all resort facilities.'],
                    ['title' => 'Guided snorkeling excursion with equipment', 'description' => 'A half-day boat excursion to the finest coral reefs in the region, led by an experienced marine guide with all snorkeling equipment — mask, fins, wetsuit, and life jacket — provided.'],
                    ['title' => 'One spa session', 'description' => 'A 60-minute treatment of your choice at the resort\'s award-winning spa — select from signature massage, rejuvenating facial, or full-body wrap.'],
                    ['title' => 'Airport transfers', 'description' => 'Private air-conditioned transfers between Hurghada International Airport and the resort on both arrival and departure days.'],
                ],
                'excludes' => [
                    ['title' => 'Flights to and from Hurghada', 'description' => 'International and domestic flights to Hurghada are not included. Our concierge can assist with flight search and booking recommendations.'],
                    ['title' => 'Egypt entry visa', 'description' => 'Most nationalities can obtain an e-Visa online before travel or a visa stamp on arrival at Hurghada Airport.'],
                    ['title' => 'Lunches', 'description' => 'Lunches are at your own expense. The resort offers several dining venues ranging from a casual poolside grill to a fine-dining restaurant.'],
                    ['title' => 'Desert safari (optional add-on)', 'description' => 'A half-day 4x4 desert safari with Bedouin-style dinner under the stars is available as a paid add-on — ask your concierge when booking.'],
                    ['title' => 'Gratuities', 'description' => 'Tips for spa therapists, resort staff, and marine guides are not included and are entirely at your discretion.'],
                ],
                'gallery' => [
                    'images/destinations/dest-hurghada.png',
                    'images/home/gallery-coral.png',
                    'images/services/service-beach-vacations.png',
                    'images/services/service-desert-safaris.png',
                ],
                'accommodations' => [
                    [
                        'name' => 'Hurghada Beachfront Resort & Spa',
                        'location' => 'Hurghada',
                        'nights' => 5,
                        'rating' => 5,
                        'image' => 'images/services/service-beach-vacations.png',
                        'description' => 'An all-inclusive beachfront resort with private lagoon access and a full-service spa.',
                    ],
                ],
                'rating_breakdown' => [
                    'itinerary' => 4.7,
                    'transportation' => 4.8,
                    'value' => 4.9,
                    'accommodation' => 4.9,
                    'tour_guide' => 4.6,
                ],
                'reviews' => [
                    [
                        'name' => 'Hannah Cohen',
                        'country' => 'Israel',
                        'date' => 'May 2026',
                        'rating' => 5,
                        'text' => 'After two weeks of temples elsewhere in Egypt, this was the perfect way to unwind - the spa and snorkeling trip were both fantastic.',
                        'photos' => [
                            'images/destinations/dest-hurghada.png',
                            'images/home/gallery-coral.png',
                        ],
                    ],
                    [
                        'name' => 'Tom Becker',
                        'country' => 'Netherlands',
                        'date' => 'March 2026',
                        'rating' => 5,
                        'text' => 'The sunset yacht cruise was the highlight of our whole holiday. Resort staff were incredibly attentive.',
                    ],
                    [
                        'name' => 'Olivia Taylor',
                        'country' => 'Australia',
                        'date' => 'January 2026',
                        'rating' => 4,
                        'text' => 'Beautiful reefs and a really relaxing resort. We added the desert safari which was a great change of pace.',
                    ],
                ],
                'faqs' => [
                    [
                        'question' => 'Is this trip suitable for non-swimmers?',
                        'answer' => 'Yes - the resort has a calm lagoon and pools for all levels, and the snorkeling excursion provides life jackets and guidance for beginners.',
                    ],
                    [
                        'question' => "What's the best time of year for this trip?",
                        'answer' => 'Hurghada is pleasant nearly year-round, but spring (March-May) and autumn (September-November) offer the most comfortable temperatures for both the beach and optional desert safari.',
                    ],
                ],
            ],

            // Curated Experiences (full trips listing)
            [
                'title' => 'Aswan Felucca Adventure',
                'slug' => 'aswan-felucca-adventure',
                'image' => 'images/trips/trip-aswan-felucca.png',
                'price' => 1250,
                'duration' => '4 Days',
                'location' => 'Aswan',
                'rating' => 4.9,
                'reviews_count' => 124,
                'destination_category' => 'Upper Egypt (Luxor/Aswan)',
                'trip_type' => 'Adventure',
                'group_size' => '2 - 10 Travelers',
                'is_featured' => false,
                'description' => "Drift along the Nile's most scenic stretch aboard a traditional felucca, where the river narrows between granite boulders and palm-lined banks. This adventure blends slow-paced sailing with visits to Nubian villages, the island temple of Philae, and the engineering marvel of the High Dam.",
                'highlights' => [
                    'Overnight sailing aboard a traditional felucca',
                    'Visit to the island Temple of Philae',
                    'Tour of the Aswan High Dam',
                    'Nubian village visit with traditional tea',
                    'Unfinished Obelisk at the ancient granite quarries',
                ],
                'itinerary' => [
                    ['day' => 1, 'title' => 'Arrival in Aswan', 'description' => 'Arrive in Aswan and check into your hotel. Afternoon visit to the Unfinished Obelisk and the High Dam.'],
                    ['day' => 2, 'title' => 'Philae Temple & Felucca Sailing', 'description' => 'Take a boat to Philae Temple, then board a felucca for a leisurely sail among Aswan\'s islands.'],
                    ['day' => 3, 'title' => 'Nubian Village', 'description' => 'Visit a colorful Nubian village by boat, enjoying traditional tea and local hospitality.'],
                    ['day' => 4, 'title' => 'Departure', 'description' => 'Free morning before transfer to Aswan International Airport or train station.'],
                ],
                'includes' => [
                    ['title' => '3 nights hotel accommodation with daily breakfast', 'description' => 'A comfortable hotel on the Aswan Corniche with Nile views and a daily full breakfast, plus one unforgettable night sleeping on deck aboard the felucca under a canopy of stars.'],
                    ['title' => 'Felucca sailing excursion', 'description' => 'A private traditional wooden sailboat crewed by experienced Nubian sailors for a relaxed drift among Aswan\'s islands and the First Cataract — the most scenic stretch of the Nile.'],
                    ['title' => 'Licensed guide and entrance fees', 'description' => 'A local Egyptologist guide accompanies you throughout, with pre-paid entry to Philae Temple, the High Dam, and all attractions listed in the itinerary.'],
                    ['title' => 'Private transfers', 'description' => 'Air-conditioned private vehicle for all transfers between the hotel, sites, and the felucca boarding point throughout the trip.'],
                ],
                'excludes' => [
                    ['title' => 'Flights or trains to/from Aswan', 'description' => 'Transport to Aswan is not included. We can assist with flight and train booking from Cairo or Luxor — the overnight sleeper train is a popular and scenic option.'],
                    ['title' => 'Egypt entry visa', 'description' => 'Most nationalities obtain an e-Visa online or on arrival at a major airport. We will confirm requirements for your specific passport before departure.'],
                    ['title' => 'Lunches and dinners', 'description' => 'Meals are at your own expense. Aswan has excellent Nubian restaurants, and the felucca crew can arrange a simple traditional meal onboard for a small additional cost.'],
                    ['title' => 'Gratuities', 'description' => 'Tips for your guide, driver, and the felucca crew are not included and are appreciated at your discretion.'],
                ],
                'gallery' => [
                    'images/destinations/dest-aswan.png',
                    'images/home/gallery-felucca.png',
                    'images/about/legacy-dahabiya-nile-dawn.png',
                ],
                'accommodations' => [
                    [
                        'name' => 'Aswan Nile-View Hotel',
                        'location' => 'Aswan',
                        'nights' => 2,
                        'rating' => 4,
                        'image' => 'images/destinations/dest-aswan.png',
                        'description' => 'A comfortable hotel overlooking the Nile and Elephantine Island, with easy access to the Corniche.',
                    ],
                    [
                        'name' => 'Traditional Felucca (Overnight Sailing)',
                        'location' => 'Nile River',
                        'nights' => 1,
                        'rating' => 4,
                        'image' => 'images/home/gallery-felucca.png',
                        'description' => "A night spent sleeping on deck under the stars as your felucca drifts gently between Aswan's islands.",
                    ],
                ],
                'rating_breakdown' => [
                    'itinerary' => 5.0,
                    'transportation' => 4.8,
                    'value' => 4.9,
                    'accommodation' => 4.7,
                    'tour_guide' => 4.9,
                ],
                'reviews' => [
                    [
                        'name' => 'Lucas Silva',
                        'country' => 'Brazil',
                        'date' => 'April 2026',
                        'rating' => 5,
                        'text' => 'Sleeping on a felucca under the stars on the Nile was one of the most peaceful nights of my life. The Nubian village visit was so welcoming.',
                        'photos' => [
                            'images/destinations/dest-aswan.png',
                            'images/home/gallery-felucca.png',
                        ],
                    ],
                    [
                        'name' => 'Mia Johansson',
                        'country' => 'Norway',
                        'date' => 'February 2026',
                        'rating' => 5,
                        'text' => 'Philae Temple by boat at sunset was stunning. Our felucca crew were wonderful hosts.',
                    ],
                    [
                        'name' => 'Ryan Walsh',
                        'country' => 'New Zealand',
                        'date' => 'December 2025',
                        'rating' => 5,
                        'text' => 'A slower, more authentic side of Egypt. Loved the High Dam visit and the unfinished obelisk.',
                    ],
                ],
                'faqs' => [
                    [
                        'question' => 'What are the sleeping arrangements on the felucca?',
                        'answer' => "You'll sleep on deck under the stars in comfortable bedding provided by the crew - a memorable, simple experience. A hotel with private rooms is used on the other nights.",
                    ],
                    [
                        'question' => 'Is the felucca sailing trip physically demanding?',
                        'answer' => 'Not at all - the crew handles the sailing, so you can simply relax, read, or chat as the Nile scenery drifts by.',
                    ],
                ],
            ],
            [
                'title' => 'Red Sea Diving Expedition',
                'slug' => 'red-sea-diving-expedition',
                'image' => 'images/trips/trip-red-sea-diving.png',
                'price' => 2400,
                'duration' => '6 Days',
                'location' => 'Sharm El Sheikh',
                'rating' => 5.0,
                'reviews_count' => 89,
                'destination_category' => 'Red Sea Riviera',
                'trip_type' => 'Adventure',
                'group_size' => '2 - 8 Divers',
                'is_featured' => false,
                'description' => "Descend into one of the world's premier diving destinations. From the sheer walls of Ras Mohammed National Park to the legendary SS Thistlegorm wreck, this expedition is built for certified divers chasing vibrant reefs, dramatic drop-offs, and unforgettable encounters beneath the Red Sea.",
                'highlights' => [
                    'Two daily dives at Ras Mohammed National Park',
                    'Wreck dive on the SS Thistlegorm',
                    'Reef dives around Tiran Island',
                    'PADI-certified dive guides',
                    'One night dive experience',
                ],
                'itinerary' => [
                    ['day' => 1, 'title' => 'Arrival & Check Dive', 'description' => 'Arrive in Sharm El Sheikh, settle into your dive resort, and complete an orientation check dive.'],
                    ['day' => 2, 'title' => 'Ras Mohammed National Park', 'description' => 'Two-tank dive day exploring the dramatic coral walls of Ras Mohammed.'],
                    ['day' => 3, 'title' => 'SS Thistlegorm Wreck', 'description' => 'Full-day boat trip to dive the famous WWII wreck of the SS Thistlegorm.'],
                    ['day' => 4, 'title' => 'Tiran Island Reefs', 'description' => 'Explore the colorful reefs surrounding Tiran Island with two guided dives.'],
                    ['day' => 5, 'title' => 'Night Dive & Free Time', 'description' => 'Relax during the day before an exhilarating guided night dive.'],
                    ['day' => 6, 'title' => 'Departure', 'description' => 'Final gear rinse and transfer to Sharm El Sheikh International Airport.'],
                ],
                'includes' => [
                    ['title' => '5 nights at a dive resort with daily breakfast', 'description' => 'A purpose-built dive resort with equipment storage, rinse tanks, daily briefing rooms, and a full breakfast each morning before hitting the water.'],
                    ['title' => 'Daily two-tank guided dives', 'description' => 'Two boat dives per day at premier sites, led by PADI-certified divemasters who know the local currents, marine life, and best entry points intimately.'],
                    ['title' => 'Full scuba equipment rental', 'description' => 'A complete set of regularly serviced equipment including BCD, regulator, wetsuit, mask, fins, tanks, and weights provided for all dive days.'],
                    ['title' => 'Airport transfers', 'description' => 'Private air-conditioned transfers between Sharm El Sheikh International Airport and the dive resort on arrival and departure days.'],
                ],
                'excludes' => [
                    ['title' => 'Flights to and from Sharm El Sheikh', 'description' => 'International and domestic flights are not included. Our concierge can assist with flight recommendations.'],
                    ['title' => 'Egypt entry visa', 'description' => 'Most nationalities can obtain an entry stamp at Sharm El Sheikh Airport specifically for the South Sinai region — we will confirm your exact requirements before travel.'],
                    ['title' => 'Diving insurance', 'description' => 'Diving insurance (such as DAN or equivalent cover) is required for all participants and is not included. Please arrange a valid policy before departure.'],
                    ['title' => 'Lunches and dinners', 'description' => 'The resort has multiple dining venues ranging from a casual poolside grill to à la carte dining, all at your own expense.'],
                    ['title' => 'Gratuities', 'description' => 'Tips for dive guides, boat crew, and resort staff are not included and are appreciated at your discretion.'],
                ],
                'gallery' => [
                    'images/destinations/dest-sharm-el-sheikh.png',
                    'images/home/gallery-coral.png',
                    'images/services/service-beach-vacations.png',
                ],
                'accommodations' => [
                    [
                        'name' => 'Sharm El Sheikh Dive Resort',
                        'location' => 'Sharm El Sheikh',
                        'nights' => 5,
                        'rating' => 5,
                        'image' => 'images/destinations/dest-sharm-el-sheikh.png',
                        'description' => 'A dedicated dive resort with an on-site equipment store, dive briefing rooms, and direct boat access.',
                    ],
                ],
                'rating_breakdown' => [
                    'itinerary' => 5.0,
                    'transportation' => 4.9,
                    'value' => 4.8,
                    'accommodation' => 4.9,
                    'tour_guide' => 5.0,
                ],
                'reviews' => [
                    [
                        'name' => 'Ethan Park',
                        'country' => 'South Korea',
                        'date' => 'May 2026',
                        'rating' => 5,
                        'text' => 'Diving the Thistlegorm wreck was a bucket-list moment - our dive guides were true professionals and the resort made everything easy.',
                        'photos' => [
                            'images/destinations/dest-sharm-el-sheikh.png',
                            'images/home/gallery-coral.png',
                        ],
                    ],
                    [
                        'name' => 'Noah Andersen',
                        'country' => 'Sweden',
                        'date' => 'March 2026',
                        'rating' => 5,
                        'text' => "Ras Mohammed's walls are unbelievable. The night dive was an unexpected highlight.",
                    ],
                    [
                        'name' => 'Anna Kowalski',
                        'country' => 'Poland',
                        'date' => 'January 2026',
                        'rating' => 5,
                        'text' => 'Perfectly organized for certified divers - equipment was top quality and the Tiran Island reefs were stunning.',
                    ],
                ],
                'faqs' => [
                    [
                        'question' => 'Do I need to be a certified diver to join this trip?',
                        'answer' => 'Yes, this itinerary is designed for divers holding at least an Open Water certification, as several dive sites involve deeper or more advanced conditions.',
                    ],
                    [
                        'question' => 'Is dive insurance included?',
                        'answer' => 'Dive insurance is not included and is required - we recommend arranging a policy (such as DAN) before you travel.',
                    ],
                ],
            ],
            [
                'title' => 'Siwa Oasis Retreat',
                'slug' => 'siwa-oasis-retreat',
                'image' => 'images/trips/trip-siwa-oasis.png',
                'price' => 1850,
                'duration' => '5 Days',
                'location' => 'Siwa',
                'rating' => 4.8,
                'reviews_count' => 56,
                'destination_category' => 'Western Desert & Oases',
                'trip_type' => 'Wellness & Retreat',
                'group_size' => '2 - 12 Travelers',
                'is_featured' => false,
                'description' => "Disconnect completely in Egypt's most remote oasis, where palm groves, mineral-rich salt lakes, and endless dunes of the Great Sand Sea create a world apart. This retreat is built around slow mornings, golden-hour 4x4 safaris, and nights spent beneath some of the clearest skies on earth.",
                'highlights' => [
                    'Great Sand Sea 4x4 desert safari',
                    'Float in Cleopatra\'s Bath salt spring',
                    'Explore the ruins of Shali Fortress',
                    'Traditional Siwan dinner under the stars',
                    'Guided stargazing session',
                ],
                'itinerary' => [
                    ['day' => 1, 'title' => 'Arrival in Siwa', 'description' => 'Arrive at your eco-lodge after the desert crossing and relax amid the palm groves.'],
                    ['day' => 2, 'title' => 'Shali Fortress & Salt Lakes', 'description' => 'Explore the mudbrick ruins of Shali Fortress, then float in the mineral-rich Cleopatra\'s Bath.'],
                    ['day' => 3, 'title' => 'Great Sand Sea Safari', 'description' => 'A thrilling 4x4 safari across towering dunes, with a stop to watch the sunset from the sand.'],
                    ['day' => 4, 'title' => 'Stargazing & Local Culture', 'description' => 'Visit a local Siwan house and enjoy a traditional dinner followed by guided stargazing.'],
                    ['day' => 5, 'title' => 'Departure', 'description' => 'Morning at leisure before the transfer journey begins.'],
                ],
                'includes' => [
                    ['title' => '4 nights at an eco-lodge with breakfast & dinner daily', 'description' => 'A traditional mudbrick eco-lodge built in Siwan style, set among palm groves with mineral spring pools, serving hearty breakfasts and dinners made from local organic ingredients.'],
                    ['title' => 'Great Sand Sea 4x4 safari', 'description' => 'A full afternoon safari across the towering dunes of the Great Sand Sea in a 4x4 vehicle with an experienced desert guide, culminating in a spectacular sunset viewed from the highest dune.'],
                    ['title' => 'Traditional Siwan dinner experience', 'description' => 'An authentic dinner prepared in a local Siwan home, featuring traditional dishes, music, and genuine Berber hospitality that very few outside visitors get to experience.'],
                    ['title' => 'Local guide throughout', 'description' => 'A knowledgeable Siwan guide accompanies you for all excursions, sharing cultural insight into the oasis\'s Berber heritage, the ancient Oracle Temple of Amun, and daily Siwan life.'],
                ],
                'excludes' => [
                    ['title' => 'Transport to and from Siwa', 'description' => 'Siwa is reached by road from Cairo (approximately 9 hours) or Marsa Matrouh. Private transfers can be arranged through our concierge at an additional cost.'],
                    ['title' => 'Egypt entry visa', 'description' => 'Most nationalities obtain an e-Visa online or on arrival at a major airport. Our team will advise on the requirements for your passport before travel.'],
                    ['title' => 'Lunches', 'description' => 'Lunches are at your own expense. The town has small local cafés and the eco-lodge can prepare a packed lunch for safari days on request for a small fee.'],
                    ['title' => 'Gratuities', 'description' => 'Tips for your guide, drivers, and the eco-lodge staff are not included and are appreciated at your discretion.'],
                ],
                'gallery' => [
                    'images/destinations/dest-siwa-oasis.png',
                    'images/services/service-desert-safaris.png',
                ],
                'accommodations' => [
                    [
                        'name' => 'Siwa Eco-Lodge & Palm Gardens',
                        'location' => 'Siwa Oasis',
                        'nights' => 4,
                        'rating' => 4,
                        'image' => 'images/destinations/dest-siwa-oasis.png',
                        'description' => 'A mudbrick eco-lodge built in traditional Siwan style, set among palm groves with mineral spring pools.',
                    ],
                ],
                'rating_breakdown' => [
                    'itinerary' => 4.8,
                    'transportation' => 4.6,
                    'value' => 4.9,
                    'accommodation' => 4.7,
                    'tour_guide' => 4.9,
                ],
                'reviews' => [
                    [
                        'name' => 'Charlotte Dubois',
                        'country' => 'Belgium',
                        'date' => 'April 2026',
                        'rating' => 5,
                        'text' => "Floating in Cleopatra's Bath at sunset and then stargazing in the Great Sand Sea - Siwa is unlike anywhere else in Egypt.",
                        'photos' => [
                            'images/destinations/dest-siwa-oasis.png',
                            'images/services/service-desert-safaris.png',
                        ],
                    ],
                    [
                        'name' => 'David Chen',
                        'country' => 'Canada',
                        'date' => 'February 2026',
                        'rating' => 4,
                        'text' => 'The 4x4 safari across the dunes was thrilling. The eco-lodge was simple but full of character.',
                    ],
                    [
                        'name' => 'Isabella Garcia',
                        'country' => 'Spain',
                        'date' => 'December 2025',
                        'rating' => 5,
                        'text' => 'Such a peaceful break from the crowds. The traditional Siwan dinner under the stars was a beautiful experience.',
                    ],
                ],
                'faqs' => [
                    [
                        'question' => 'How do I get to Siwa Oasis?',
                        'answer' => 'Siwa is reached by a scenic road journey from Cairo or Marsa Matrouh. Transport is not included in this package, but our concierge can help arrange a private transfer.',
                    ],
                    [
                        'question' => "What's the weather like in the desert at night?",
                        'answer' => 'Days are warm but desert nights can be cool, especially during the stargazing session - we recommend packing a light jacket even in summer.',
                    ],
                ],
            ],
            [
                'title' => 'Pyramid Heritage Tour',
                'slug' => 'pyramid-heritage-tour',
                'image' => 'images/trips/trip-pyramid-heritage.png',
                'price' => 890,
                'duration' => '3 Days',
                'location' => 'Cairo',
                'rating' => 4.9,
                'reviews_count' => 210,
                'destination_category' => 'Cairo & Giza',
                'trip_type' => 'Historical Discovery',
                'group_size' => '2 - 16 Travelers',
                'is_featured' => false,
                'description' => "A focused, fast-paced introduction to Egypt's most iconic monuments. In just three days, stand before the Great Pyramids, descend into the Step Pyramid of Saqqara, and come face to face with Tutankhamun's treasures — perfect for travelers short on time but not on wonder.",
                'highlights' => [
                    'Great Pyramids of Giza & the Great Sphinx',
                    'Solar Boat Museum exhibit',
                    'Step Pyramid of Djoser at Saqqara',
                    'Highlights tour of the Egyptian Museum',
                ],
                'itinerary' => [
                    ['day' => 1, 'title' => 'Arrival & Giza Plateau', 'description' => 'Arrive in Cairo and head straight to Giza to see the Pyramids, the Sphinx, and the Solar Boat Museum.'],
                    ['day' => 2, 'title' => 'Saqqara & Egyptian Museum', 'description' => 'Visit the Step Pyramid of Djoser at Saqqara in the morning, then explore the Egyptian Museum\'s highlights.'],
                    ['day' => 3, 'title' => 'Departure', 'description' => 'Free morning for last-minute shopping before transfer to Cairo International Airport.'],
                ],
                'includes' => [
                    ['title' => '2 nights hotel accommodation with daily breakfast', 'description' => 'A centrally located 4-star hotel in Giza with rooftop views of the Great Pyramids and a full breakfast every morning for early starts to the sites.'],
                    ['title' => 'Licensed Egyptologist guide', 'description' => 'A university-qualified Egyptologist accompanies you for all three days, providing expert commentary at the Pyramids, Saqqara, and the Egyptian Museum highlights gallery.'],
                    ['title' => 'All entrance fees listed in the itinerary', 'description' => 'Pre-paid access to the Giza Plateau, Great Sphinx, Solar Boat Museum, Step Pyramid of Saqqara, and the Egyptian Museum highlights — no queuing at ticket booths.'],
                    ['title' => 'Private air-conditioned transport', 'description' => 'A private vehicle and dedicated driver for all transfers between Cairo Airport, the hotel, and every site on the itinerary.'],
                ],
                'excludes' => [
                    ['title' => 'International flights', 'description' => 'Flights to and from Cairo International Airport are not included. Our concierge can assist with flight search and booking recommendations.'],
                    ['title' => 'Egypt entry visa', 'description' => 'Most nationalities obtain an e-Visa online before travel or at the airport on arrival. We will confirm the exact requirement for your passport before you depart.'],
                    ['title' => 'Lunches and dinners', 'description' => 'All meals beyond the daily included breakfast are at your own expense. Cairo has a vast range of restaurants — your guide will be happy to recommend favorites.'],
                    ['title' => 'Gratuities', 'description' => 'Tips for your guide and driver are not included and entirely at your discretion. A tipping guideline is provided in your pre-departure information pack.'],
                ],
                'gallery' => [
                    'images/home/hero-pyramids.png',
                    'images/destinations/dest-cairo.png',
                    'images/about/mission-archaeological-discovery.png',
                ],
                'accommodations' => [
                    [
                        'name' => 'Giza Pyramids View Hotel',
                        'location' => 'Giza',
                        'nights' => 2,
                        'rating' => 5,
                        'image' => 'images/contact/office-cairo-pyramids-view.png',
                        'description' => 'A comfortable hotel with rooftop views of the Great Pyramids, perfectly placed for early starts.',
                    ],
                ],
                'rating_breakdown' => [
                    'itinerary' => 4.9,
                    'transportation' => 4.8,
                    'value' => 5.0,
                    'accommodation' => 4.7,
                    'tour_guide' => 4.9,
                ],
                'reviews' => [
                    [
                        'name' => 'Pedro Alves',
                        'country' => 'Portugal',
                        'date' => 'May 2026',
                        'rating' => 5,
                        'text' => 'Perfect for a short stopover - we covered the pyramids, Saqqara and the museum without feeling rushed at all.',
                        'photos' => [
                            'images/home/hero-pyramids.png',
                            'images/destinations/dest-cairo.png',
                        ],
                    ],
                    [
                        'name' => 'Grace Kim',
                        'country' => 'South Korea',
                        'date' => 'March 2026',
                        'rating' => 5,
                        'text' => "Our guide's explanations at Saqqara made the Step Pyramid the highlight, even more than Giza for me.",
                    ],
                    [
                        'name' => 'Felix Wagner',
                        'country' => 'Austria',
                        'date' => 'January 2026',
                        'rating' => 4,
                        'text' => 'Great value for 3 days. Hotel was comfortable and well located for early starts.',
                    ],
                ],
                'faqs' => [
                    [
                        'question' => 'Can this tour be done as a day trip from the airport?',
                        'answer' => 'While the core sites can be visited in a single long day, we recommend the 2-night stay included in this package so you can explore at a relaxed pace without rushing back for a flight.',
                    ],
                    [
                        'question' => 'Is entry inside the Great Pyramid included?',
                        'answer' => 'The Great Pyramid exterior, Sphinx, and Solar Boat Museum are included; entry inside the pyramid chambers requires an additional ticket purchased on-site, which your guide can arrange.',
                    ],
                ],
            ],
            [
                'title' => 'Dahabiya Private Cruise',
                'slug' => 'dahabiya-private-cruise',
                'image' => 'images/trips/trip-dahabiya-cruise.png',
                'price' => 3100,
                'duration' => '7 Days',
                'location' => 'Nile Cruise',
                'rating' => 5.0,
                'reviews_count' => 42,
                'destination_category' => 'Upper Egypt (Luxor/Aswan)',
                'trip_type' => 'Wellness & Retreat',
                'group_size' => '2 - 8 Guests (Private Charter)',
                'is_featured' => false,
                'description' => "Sail between Luxor and Aswan the way explorers once did — aboard a private dahabiya with your own crew, chef, and sun deck. Free from the crowds of larger cruise ships, this week-long voyage glides past temples, riverside villages, and golden sands at the unhurried pace of the wind.",
                'highlights' => [
                    'Private dahabiya with dedicated crew and chef',
                    'Temples of Edfu and Kom Ombo',
                    'Valley of the Kings & Karnak Temple',
                    'Sunset sailing with sun deck lounging',
                    'Chef-prepared meals using local ingredients',
                ],
                'itinerary' => [
                    ['day' => 1, 'title' => 'Embarkation in Luxor', 'description' => 'Board your dahabiya in Luxor and settle into your cabin before an evening visit to Karnak Temple.'],
                    ['day' => 2, 'title' => 'Valley of the Kings', 'description' => 'Cross to the West Bank to explore the Valley of the Kings and Hatshepsut\'s Temple.'],
                    ['day' => 3, 'title' => 'Sailing to Esna', 'description' => 'Set sail downriver toward Esna, enjoying the changing scenery from the sun deck.'],
                    ['day' => 4, 'title' => 'Edfu Temple', 'description' => 'Visit the remarkably preserved Temple of Horus at Edfu before continuing south.'],
                    ['day' => 5, 'title' => 'Kom Ombo', 'description' => 'Explore the riverside Temple of Kom Ombo, dedicated to the crocodile god Sobek.'],
                    ['day' => 6, 'title' => 'Arrival in Aswan', 'description' => 'Arrive in Aswan and visit the High Dam and Philae Temple by boat.'],
                    ['day' => 7, 'title' => 'Disembarkation', 'description' => 'Enjoy a final breakfast on board before disembarking and transferring onward.'],
                ],
                'includes' => [
                    ['title' => '6 nights in a private dahabiya cabin', 'description' => 'A spacious en-suite cabin aboard your traditional private sailboat, with a shared sun deck, seating lounge, and panoramic Nile views throughout the entire Luxor-to-Aswan voyage.'],
                    ['title' => 'Full board with chef-prepared meals', 'description' => 'A dedicated on-board chef prepares three fresh meals daily using local produce, with menus tailored to your dietary preferences and served under the stars or on the shaded deck.'],
                    ['title' => 'All sightseeing tours and entrance fees', 'description' => 'Pre-paid access to all temples and monuments in the itinerary — Karnak, Valley of the Kings, Edfu, Kom Ombo, the Aswan High Dam, and Philae — with a private Egyptologist guide.'],
                    ['title' => 'Private Egyptologist guide', 'description' => 'A licensed Egyptologist joins you for all shore excursions, providing expert commentary, private access where available, and the freedom to linger as long as you like at each site.'],
                ],
                'excludes' => [
                    ['title' => 'Flights to and from Luxor/Aswan', 'description' => 'International and domestic flights are not included. Our concierge can assist with flight booking to Luxor and return flights from Aswan.'],
                    ['title' => 'Egypt entry visa', 'description' => 'Most nationalities can obtain an e-Visa online before travel or on arrival at major airports. Our team will confirm the exact requirement for your passport.'],
                    ['title' => 'Beverages and bar bills', 'description' => 'Soft drinks, alcoholic beverages, mineral water beyond mealtimes, and any bar charges on board are at your own expense.'],
                    ['title' => 'Gratuities for crew and guide', 'description' => 'Tips for the captain, sailing crew, chef, and your Egyptologist guide are not included. A suggested tipping guideline will be provided in your pre-departure documents.'],
                ],
                'gallery' => [
                    'images/about/legacy-dahabiya-nile-dawn.png',
                    'images/destinations/dest-luxor.png',
                    'images/home/gallery-felucca.png',
                ],
                'accommodations' => [
                    [
                        'name' => 'Private Dahabiya - En-Suite Cabin',
                        'location' => 'Nile River (Luxor to Aswan)',
                        'nights' => 6,
                        'rating' => 5,
                        'image' => 'images/about/legacy-dahabiya-nile-dawn.png',
                        'description' => 'A spacious en-suite cabin aboard a traditional sailboat, with a shared sun deck and dedicated crew throughout the voyage.',
                    ],
                ],
                'rating_breakdown' => [
                    'itinerary' => 5.0,
                    'transportation' => 4.9,
                    'value' => 4.8,
                    'accommodation' => 5.0,
                    'tour_guide' => 5.0,
                ],
                'reviews' => [
                    [
                        'name' => 'Amara Okafor',
                        'country' => 'Nigeria',
                        'date' => 'April 2026',
                        'rating' => 5,
                        'text' => 'Having the dahabiya to ourselves with a private chef was pure luxury - sailing past Edfu and Kom Ombo at our own pace was magical.',
                        'photos' => [
                            'images/about/legacy-dahabiya-nile-dawn.png',
                            'images/destinations/dest-luxor.png',
                        ],
                    ],
                    [
                        'name' => 'Daniel Cohen',
                        'country' => 'Israel',
                        'date' => 'February 2026',
                        'rating' => 5,
                        'text' => 'The most romantic way to see the Nile. Crew went above and beyond every single day.',
                    ],
                    [
                        'name' => 'Laura Bianchi',
                        'country' => 'Italy',
                        'date' => 'December 2025',
                        'rating' => 5,
                        'text' => 'Worth every penny - Kom Ombo at sunset from the sun deck was unforgettable.',
                    ],
                ],
                'faqs' => [
                    [
                        'question' => 'How many cabins does the dahabiya have?',
                        'answer' => 'Our dahabiyas typically have 4-8 en-suite cabins, and we can arrange a full private charter for your group - ask your concierge for current vessel availability.',
                    ],
                    [
                        'question' => 'Is this cruise suitable for travelers with limited mobility?',
                        'answer' => 'Dahabiyas have narrow stairways between decks and require some walking at temple sites, so this trip is best suited to travelers who are reasonably mobile.',
                    ],
                ],
            ],
            [
                'title' => 'Abu Simbel Dawn Tour',
                'slug' => 'abu-simbel-dawn-tour',
                'image' => 'images/trips/trip-abu-simbel-dawn.png',
                'price' => 720,
                'duration' => '2 Days',
                'location' => 'Abu Simbel',
                'rating' => 4.7,
                'reviews_count' => 156,
                'destination_category' => 'Upper Egypt (Luxor/Aswan)',
                'trip_type' => 'Historical Discovery',
                'group_size' => '2 - 16 Travelers',
                'is_featured' => false,
                'description' => "Witness the colossal rock-cut temples of Ramses II and Nefertari at first light, when the desert sun paints the facades of Abu Simbel in gold. A short, dramatic escape from Aswan to one of the most awe-inspiring monuments ever carved by human hands.",
                'highlights' => [
                    'Sunrise arrival at Abu Simbel before the crowds',
                    'Great Temple of Ramses II',
                    'Temple of Hathor & Nefertari',
                    'Scenic views over Lake Nasser',
                ],
                'itinerary' => [
                    ['day' => 1, 'title' => 'Aswan Arrival', 'description' => 'Arrive in Aswan and check into your hotel, with an early night ahead of tomorrow\'s departure.'],
                    ['day' => 2, 'title' => 'Abu Simbel at Sunrise', 'description' => 'Depart before dawn for Abu Simbel, exploring the Great Temple of Ramses II and the Temple of Hathor as the sun rises, before returning to Aswan.'],
                ],
                'includes' => [
                    ['title' => '1 night hotel accommodation in Aswan with breakfast', 'description' => 'A comfortable hotel on the Aswan Corniche the night before your dawn departure, with a hearty breakfast provided before the early start to Abu Simbel.'],
                    ['title' => 'Round-trip transport to Abu Simbel', 'description' => 'Private air-conditioned vehicle for the 3-hour drive from Aswan to Abu Simbel and return — departing well before sunrise to arrive at the temples in soft golden light before the crowds.'],
                    ['title' => 'Licensed guide and entrance fees', 'description' => 'A licensed guide accompanies you throughout with expert insight into Ramses II\'s extraordinary rock-cut temples and the engineering feat of their UNESCO relocation. All entrance fees are pre-paid.'],
                ],
                'excludes' => [
                    ['title' => 'Flights or trains to/from Aswan', 'description' => 'Travel to Aswan from elsewhere in Egypt is not included. Our team can assist with train or flight booking from Cairo or Luxor.'],
                    ['title' => 'Egypt entry visa', 'description' => 'Most nationalities obtain an e-Visa online or on arrival at a major Egyptian airport.'],
                    ['title' => 'Lunches and dinners', 'description' => 'Meals beyond the included Aswan breakfast are at your own expense. Aswan has a good range of Nile-side restaurants.'],
                    ['title' => 'Gratuities', 'description' => 'Tips for your guide and driver are not included and are appreciated at your discretion.'],
                ],
                'gallery' => [
                    'images/home/gallery-abu-simbel.png',
                    'images/destinations/dest-aswan.png',
                ],
                'accommodations' => [
                    [
                        'name' => 'Aswan Nile-View Hotel',
                        'location' => 'Aswan',
                        'nights' => 1,
                        'rating' => 4,
                        'image' => 'images/destinations/dest-aswan.png',
                        'description' => 'A comfortable base on the Aswan Corniche, ideally placed for an early departure to Abu Simbel.',
                    ],
                ],
                'rating_breakdown' => [
                    'itinerary' => 4.8,
                    'transportation' => 4.6,
                    'value' => 4.9,
                    'accommodation' => 4.5,
                    'tour_guide' => 4.8,
                ],
                'reviews' => [
                    [
                        'name' => 'Yuki Tanaka',
                        'country' => 'Japan',
                        'date' => 'May 2026',
                        'rating' => 5,
                        'text' => 'Watching the sun illuminate the temple facade at dawn gave me chills. Well worth the early start from Aswan.',
                        'photos' => [
                            'images/home/gallery-abu-simbel.png',
                            'images/destinations/dest-aswan.png',
                        ],
                    ],
                    [
                        'name' => 'Noor Al-Sayed',
                        'country' => 'United Arab Emirates',
                        'date' => 'March 2026',
                        'rating' => 4,
                        'text' => "Long day but completely worth it - the scale of the temples is hard to comprehend until you're standing there.",
                    ],
                    [
                        'name' => 'Sophie Dubois',
                        'country' => 'France',
                        'date' => 'January 2026',
                        'rating' => 5,
                        'text' => 'A short but unforgettable add-on to our Aswan stay. Our driver and guide were fantastic.',
                    ],
                ],
                'faqs' => [
                    [
                        'question' => 'Why does the tour depart so early?',
                        'answer' => 'Abu Simbel is a 3-hour drive from Aswan, and arriving at sunrise lets you experience the temples in soft golden light before the crowds and midday heat arrive.',
                    ],
                    [
                        'question' => 'Can I fly to Abu Simbel instead of driving?',
                        'answer' => "Yes, short flights from Aswan are available for an additional cost - let us know when booking if you'd prefer to fly rather than join the road convoy.",
                    ],
                ],
            ],
        ];

        foreach ($trips as $index => $trip) {
            Trip::create($trip + ['order' => $index]);
        }
    }
}
